### ISSUE TITLE
代码问题 第 473 行

### ISSUE THREAD

**Issue by ghost** [thunlp/SE-WRL-SAT#11]
您好！

在代码 SAT_new.c 的第 473 行，223 是什么的数值？难道是某词语最大的义原个数？

**Comment by heyLinsir** [comment]
223可以理解成最大的义原个数，实际上没有单词具有这么多义原，设置成223只是为了保证空间足够。您也可以设置成其他值，只要大于最大义原个数就行。

**Comment by ghost** [comment]
> 223可以理解成最大的义原个数，实际上没有单词具有这么多义原，设置成223只是为了保证空间足够。您也可以设置成其他值，只要大于最大义原个数就行。

谢谢您的回复！
建议您下次写成宏定义，这样能好懂一些，我多嘴了。
