### ISSUE TITLE
单义词义元信息的利用

### ISSUE THREAD

**Issue by Saltychtao** [thunlp/SE-WRL-SAT#13]
你好，我注意到Word_Sense_Sememe_File.txt文件里的词都是多义词，每个都有多组义元。请问hownet中单义词的义元标注信息是没有用到吗？如果把这个也用上去，模型的性能会有所提高吗？ 毕竟，hownet中大部分的词都是单义词。

**Comment by Fanchao-Qi** [comment]
是的，目前的模型没有利用单义词义原信息。因为SAT模型本身利用义原信息起到一个词义消歧的作用。
理论上可以使用单义词的义原信息，我们没有尝试过，欢迎尝试并分享结果。

**Comment by Fanchao-Qi** [comment]
是的，目前的模型没有利用单义词义原信息。因为SAT模型本身利用义原信息起到一个词义消歧的作用。
理论上可以使用单义词的义原信息，我们没有尝试过，欢迎尝试并分享结果。
