### ISSUE TITLE
关于SogouT训练的词向量

### ISSUE THREAD

**Issue by shuizhonghaitong** [thunlp/SE-WRL-SAT#16]
您好！请问SogouT的语料，您是Clean-SogouT1.tgz和Clean-SogouT2.tgz都有用到吗？是用gensim的word2vec还是google的word2vec训练的呢？用gensim训练的话编码貌似有些问题。。

**Comment by Fanchao-Qi** [comment]
是的，都用到了。
你指的是baseline的SG和CBOW么？是用的google的word2vec训练的。
