### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by findhomebythesea** [thunlp/SE-WRL-SAT#4]
您好！代码方面有个问题需要问您一下：
// get "attention" result on senses
              for (p = 0; p < word_senses[target].num; ++p) {
                _exp[p] = _exp[p] / temp_total;
                for (q = 0; q < vec_dim; ++q) {
                  attention[q] += _exp[p] * word_senses[target].sense_vecs[p * vec_dim + q];
                  attention_avg[q] += _exp[p] * avg_sememe[p * vec_dim + q];
                }
              }
              total = temp_total;
            }
其中的 attention[q]和attention_avg[q]，分别代表什么？

**Comment by thuqinyj16** [comment]
attention[q]是每个词的各个词义在上下文上做attention后重新加和的结果；attention_avg是每个词的各个词义的义原的均值在上下文做attention后重新加和的结果，本质上应该没有区别，只是方便于后续back propagation中使用
