### ISSUE TITLE
about new version

### ISSUE THREAD

**Issue by embraceth** [thunlp/SE-WRL-SAT#5]
您好，请问另两个模型的新版本代码什么时候会上传？非常需要另两个模型的新代码。感谢！！
另外问一下您，对于训练时间的统计，real，user和sys分别代表什么时间。

**Comment by Fanchao-Qi** [comment]
你好，目前我们暂无人力更新另外两个模型的代码。
其实最简单的方法只需要将新代码的`TrainModelThread`函数替换为其他两个模型的相应的函数，同时做出其他细节的修改，就可以完成对旧代码大部分的更新。

关于三个不同的时间，可以参考[这个回答](http://stackoverflow.com/a/556411/2223706)。

**Comment by embraceth** [comment]
ok，感谢！
