### ISSUE TITLE
issue about code

### ISSUE THREAD

**Issue by findhomebythesea** [thunlp/SE-WRL-SAT#6]
for (p = 0; p < vec_dim; ++p)
                mult_part[p] = g * word_vec[p + l1] * context_vec[p];
              real avg_num;
              for (p = 0; p < word_senses[target].num; ++p) {
                if (p == 0)
                  avg_num = 1.0 / (real)(word_senses[target].sememe_num_acc[0]);
                else
                  avg_num = 1.0 / (real)(word_senses[target].sememe_num_acc[p] - word_senses[target].sememe_num_acc[p - 1]);
                real *temp_mult = &(word_senses[target].sense_vecs[p * vec_dim]);
                for (c = 0; c < vec_dim; ++c) {
                  mult_part2[c] = mult_part[c] * (temp_mult[c] - attention[c]) * _exp[p] * avg_num;
                }
                for (q = (p == 0 ? 0 : word_senses[target].sememe_num_acc[p - 1]); q < word_senses[target].sememe_num_acc[p]; ++q) {
                  real *temp = &(sememe_vec[word_senses[target].sememe_idx[q] * vec_dim]);
                  for (c = 0; c < vec_dim; ++c) {
                    temp[c] += mult_part2[c];
您好，代码这边应该是对于sememe_vec的更新，所以我想问一下，mult_part2[c] = mult_part[c] * (temp_mult[c] - attention[c]) * _exp[p] * avg_num;中的(temp_mult[c] - attention[c]) * _exp[p]是啥意思？是公式推出来的吗？感谢!

**Comment by heyLinsir** [comment]
mult_part2对应的是当前单词中，第p个sense所对应的sememe_vec的梯度。因为所有sememe_vec梯度一样，所以提前计算出来存到了mult_part2中。
(temp_mult[c] - attention[c]) * _exp[p]是推出来的梯度公式中的一部分。temp_mult是第p个sense对应的向量表示；attention是所有sense_vec的加权平均结果；_exp[p]对应的是第p个sense的权重。

**Comment by findhomebythesea** [comment]
嗯，可能我自己写的损失函数不对，您这边还有那个损失函数的公式吗？能不能简单的打一下，提供一下，谢谢！

**Comment by heyLinsir** [comment]
留一下你的邮箱，我给你发图吧。

**Comment by findhomebythesea** [comment]
15315957258@163.com，谢谢

**Comment by liuyijiang1994** [comment]
你好，想请教一下这里sememe_vec是如何更新的？比如sememe_vec中vec的更新对应的是哪一行？
