### ISSUE TITLE
在Word_Sense_Sememe_File.txt  添加1w个新词 的义原的时候报错

### ISSUE THREAD

**Issue by bestpredicts** [thunlp/SE-WRL-SAT#7]
按照Word_Sense_Sememe_File.txt原有的格式 添加里面没有的词 及其义原  训练  添加几十个的时候程序不报错 ，1w个就报错了。
Command terminated by signal 11
145.23user 1.74system 2:27.02elapsed 99%CPU (0avgtext+0avgdata 1278968maxresident)k
0inputs+7080outputs (0major+354194minor)pagefaults 0swaps

**Comment by Fanchao-Qi** [comment]
你好，添加的新词的义原是否在`SememeFile.txt`中？

**Comment by bestpredicts** [comment]
> 你好，添加的新词的义原是否在`SememeFile.txt`中？

在的  新词的义原是根据你们义原推荐的那个论文的的代码跑出来 划分的 我把新添加的词及其义原传到网盘上了 你们可以下载添加到Word_Sense_Sememe_File.txt结尾  复现一下,使用的语料是Sougou的语料 
  https://pan.baidu.com/s/1H_L7uc3tas-lAf1-VKx-PQ

**Comment by Fanchao-Qi** [comment]
> > 你好，添加的新词的义原是否在`SememeFile.txt`中？
> 
> 在的 新词的义原是根据你们义原推荐的那个论文的的代码跑出来 划分的 我把新添加的词及其义原传到网盘上了 你们可以下载添加到Word_Sense_Sememe_File.txt结尾 复现一下,使用的语料是Sougou的语料
> [pan.baidu.com/s/1H_L7uc3tas-lAf1-VKx-PQ](https://pan.baidu.com/s/1H_L7uc3tas-lAf1-VKx-PQ)

更新了代码和义原文件`SememeFile.txt`，你试一下新的代码。

**Comment by bestpredicts** [comment]
> > > 你好，添加的新词的义原是否在`SememeFile.txt`中？
> > 
> > 
> > 在的 新词的义原是根据你们义原推荐的那个论文的的代码跑出来 划分的 我把新添加的词及其义原传到网盘上了 你们可以下载添加到Word_Sense_Sememe_File.txt结尾 复现一下,使用的语料是Sougou的语料
> > [pan.baidu.com/s/1H_L7uc3tas-lAf1-VKx-PQ](https://pan.baidu.com/s/1H_L7uc3tas-lAf1-VKx-PQ)
> 
> 更新了代码和义原文件`SememeFile.txt`，你试一下新的代码。
感谢 更新的代码解决了我的问题

**Comment by bestpredicts** [comment]
添加100个新词及其对应的 义原到 Word_Sense_Sememe_File.txt文件末尾中，训练，又出现了上面的错误。 添加的100个新词及其义原 文件链接：https://pan.baidu.com/s/1PzWAYbC9VT_v_OaaZIh7LA
