### ISSUE TITLE
并没有支持义原表没有的义原

### ISSUE THREAD

**Issue by bestpredicts** [thunlp/SE-WRL-SAT#8]
在Word_Sense_Sememe_File.txt  末尾添加一行  
`剥夺 2 1 剥夺 1 剥夺`  
程序报错，应该剥夺这个义原的问题 把剥夺换成别的义原就可以了，所以并没有支持义原表没有的义原？

**Comment by Fanchao-Qi** [comment]
使用的是最新的代码吗？ 参考 #7

**Comment by bestpredicts** [comment]
> 使用的是最新的代码吗？ 参考 #7

是使用最新的代码，我再把义原表中没有的义原去掉以后程序就正常了，不过还有一个想请教的，我在Word_Sense_Sememe_File.txt添加了3个扩展的知网的词以后，训练程序跑到5.3%的时候，会有free()函数内存报错的问题，是不是数组定义的大小有问题？

**Comment by Fanchao-Qi** [comment]
你好，如果修改`Word_Sense_Sememe_File.txt`，需要相应地在代码中更改数组大小等的设置，不然确实会出现内存报错的问题。

**Comment by Anthony1013** [comment]
> 使用的是最新的代码吗？ 参考 #7

您好，最新的代码的百度网盘已经取消了，能再发一份吗。我也是在加入新的义原的时候报核心已转储的错误。 谢谢您。
邮箱：lengjd@126.com
