### ISSUE TITLE
更新后的论文缺少字体

### ISSUE THREAD

**Issue by ghost** [thunlp/SE-WRL-SAT#9]
更新后的论文(http://thunlp.org/~lzy/publications/acl2017_sememe.pdf)打不开，提示缺少字体 “kanerc+cmmi8”，但是这种字体全网都下不到。能否重新发布一个兼容windows的论文？

**Comment by Fanchao-Qi** [comment]
windows试过没问题啊，你换一个PDF阅读器试试呢（e.g., Acrobat，福昕，PDF-X Viewer）

**Comment by ghost** [comment]
@Fanchao-Qi 我是用 Acrobat 和 chrome 打开的，公式里的字母都不显示。

**Comment by Fanchao-Qi** [comment]
你好，无法复现此问题，现在这个问题还存在吗？

**Comment by ghost** [comment]
> 你好，无法复现此问题，现在这个问题还存在吗？

你好，该问题可能已被修复了。刚才试了一下，在windows下使用wps打开不报错。

**Comment by Fanchao-Qi** [comment]
好的。
